spring:
  profiles:
    active:
      - "gen"
  main:
    web-application-type: NONE
  datasource:
    # HikariCP settings
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolOBridge


# Logging settings
logging:
  level:
    root: info
    org.obridge: info
  file:
    name: obridge.log

# OBridge defaults
obridge:
  generate-nested-types: true
  packages:
    converter-objects: converters
    procedure-context-objects: context
    package-objects: packages
    entity-objects: objects
  logging:
    initializer: private static final java.util.logging.Logger LOGGER = java.util.logging.Logger.getLogger(%s.class.getName());
    method: LOGGER.info
